package server.interfaces;

public enum OperationsEnum {
	BORROW_ITEM,FIND_ITEM,RETURN_ITEM, ADD_TO_WAITING_LIST, BOOK_BORROWED, BOOK_AVAILABLE/*, UPDATE_DB, UPDATE_SEQUENCE_NUMBER, RECOVER_SERVER, HEARTBEAT*/;
}
